import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: '700'
});

export const metadata: Metadata = {
  title: "ArtLab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[var(--dark-color)] text-[var(--light-color)] ${ubuntu.variable} antialiased `}
      >
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
